update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,16 +17,6 @@ jobs:
           pip install -r requirements.txt
           python manage.py test taskManager
 
-  integration:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run:
-          command: |
-            echo "This is an integration step"
-            exit 1
-
   oast-frontend:
     machine: true
     steps:
@@ -39,11 +29,23 @@ jobs:
       - run:
           name: Run RetireJS
           command: |
-            docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-output.json --severity high
+            docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-output.json --severity high || true
 
       - store_artifacts:
           path: retirejs-output.json
           destination: retirejs-artifact
+          when: always
+
+  integration:
+    docker:
+      - image: python:3.6
+    steps:
+      - checkout
+      - run:
+          command: |
+            echo "This is an integration step"
+            exit 1
+          when: on_fail         # Even if the job fails, continue to the next stages
 
   prod:
     docker:
@@ -62,10 +64,10 @@ workflows:
             - build
       - oast-frontend:
           requires:
-            - tesr
+            - test
       - integration:
-          require:
-            -  oast-frontend
+          requires:
+            - oast-frontend
       - prod:
           type: approval
           requires:
